export const Text = {
  baseStyle: {
    fontFeatureSettings:
      '"ss07" on, "ss02" on, "ss03" on, "ss04" on, "ss05" on, "ss06" on',
    fontFamily: 'Helvetica Now Text, sans-serif', // set the default fontFamily
    fontSize: '14px', // set the default fontSize
    fontWeight: '400', // set the default fontWeight
    lineHeight: '20px', // set the default lineHeight
    letterSpacing: '0.005em', // set the default letterSpacing
    textAlign: 'left', // set the default textAlign
  },
  variants: {
    display: {
      fontFamily: `'Helvetica Now Display', sans-serif`,
    },
    titleL: {
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '40px',
      fontWeight: '900',
      lineHeight: '40px',
      letterSpacing: '0em',
      textAlign: 'center',
    },
    titleM: {
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '32px',
      fontWeight: '900',
      lineHeight: '32px',
      letterSpacing: '0em',
      textAlign: 'center',
    },
    titleS: {
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '24px',
      fontWeight: '900',
      lineHeight: '24px',
      letterSpacing: '0.01em',
      textAlign: 'center',
    },
    titleXS: {
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '20px',
      fontWeight: '900',
      lineHeight: '20px',
      letterSpacing: '0.01em',
      textAlign: 'left',
    },
    contentTitleXS: {
      h: '40px',
      py: '8px',
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '20px',
      fontWeight: '900',
      lineHeight: '20px',
      letterSpacing: '0.01em',
      textAlign: 'left',
    },
    titleXXS: {
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '16px',
      fontWeight: '900',
      lineHeight: '16px',
      letterSpacing: '0.02em',
      textAlign: 'left',
    },
    largeBold: {
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '18px',
      fontWeight: '700',
      lineHeight: '28px',
      letterSpacing: '-0.005em',
      textAlign: 'center',
    },
    large: {
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '18px',
      fontWeight: '400',
      lineHeight: '28px',
      letterSpacing: '0em',
      textAlign: 'center',
    },
    mediumBold: {
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '16px',
      fontWeight: '700',
      lineHeight: '24px',
      letterSpacing: '0em',
      textAlign: 'left',
    },
    medium: {
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '14px',
      fontWeight: '700',
      lineHeight: '20px',
      letterSpacing: '0.005em',
      textAlign: 'left',
    },
    regular: {
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '24px',
      letterSpacing: '0.005em',
      textAlign: 'left',
    },
    tagText: {
      display: 'flex',
      gap: '8px',
      justifyContent: 'center',
      alignItems: 'center',
      direction: 'row',
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '14px',
      fontWeight: '700',
      lineHeight: '20px',
      letterSpacing: '0.005em',
      textAlign: 'left',
      h: '40px',
      p: '10px 16px',
      boxShadow: '0px 8px 24px 0px #0A20390A',
      rounded: '8px',
      bg: 'white',
    },
    contentDescription: {
      fontFamily: 'Helvetica Now Text, sans-serif',
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '24px',
      letterSpacing: '0.005em',
      textAlign: 'left',
      color: 'neutral.550',
    },
    seeAll: {
      fontFamily: 'Helvetica Now Display, sans-serif',
      fontSize: '16px',
      fontWeight: '700',
      lineHeight: '24px',
      letterSpacing: '0.005em',
      textAlign: 'left',
      color: 'orange.50',
    },
  },
}
