export const zIndices = {
  appHeader: 2,
  gradientFade: 4,
  menu: 100,
  searchInput: 3,
  programFilter: 1,
  progressPhotosUploadCarousel: 100,
  responsiveCarousel: 500,
  toast: 10000,
  workoutCardDefault: 100,
  workoutCardThumbnailFlex: 1000,
  workoutCardThumbnail: 1,
  workoutCarousel: 100,
  commentMedia: 1,
  mediaCarousel: 2,
  profilePicture: 1000,
  welcomeLayoutFirst: 300,
  welcomeLayoutSecond: 200,
  contentPage: 100,
  welcomePage: 500,
  formTheme: 0,
  contentButtons: 1,
}
